### ISSUE TITLE
配置好后我引用消息后，并没有得到回复，但后台是显示已经输出出来了，不知道是什么原因

### ISSUE THREAD

**Issue by AnCool-OvO** [wangxyd/ipartment#1]
@wangxyd

**Comment by AnCool-OvO** [comment]
![微信图片_20240423103242](https://github.com/wangxyd/ipartment/assets/144927814/aac6e7e3-ac0f-42ad-ad87-d4f1902d6612)

就是这里我发你好就可以正常发送出来，但问他新闻他就发不出来了，但后台这边是正常可以输出出来的，但并没有发出

![1](https://github.com/wangxyd/ipartment/assets/144927814/36a162c1-925b-48d4-a4ab-dedeeef2d8b9)

**Comment by wangxyd** [comment]
第二张图片日志内容不全，看不出来具体是什么问题。
根据描述，意思是CoW发送了回复消息但是微信并没有接收到？如果这个问题的话，大概是消息包含敏感内容被微信吞了。

**Comment by AnCool-OvO** [comment]
> 第二张图片日志内容不全，看不出来具体是什么问题。 根据描述，意思是CoW发送了回复消息但是微信并没有接收到？如果这个问题的话，大概是消息包含敏感内容被微信吞了。


对的，我刚才把插件卸载了，还是有这个不清楚是什么情况， 我早上发的时候还是可以发的，然后现在我测试的是私聊是可以正常发出来的，但是群聊的话就不行了
下面是完整的日志
![2](https://github.com/wangxyd/ipartment/assets/144927814/0a80a42a-0fac-454f-a239-1929fbf033a2)

**Comment by wangxyd** [comment]
那就确定是消息里面包含敏感内容，私聊可以发送，但是无法发在群里。
你试试不包含敏感内容的消息，肯定能在群聊里面发送。

**Comment by AnCool-OvO** [comment]
> 那就确定是消息里面包含敏感内容，私聊可以发送，但是无法发在群里。 你试试不包含敏感内容的消息，肯定能在群聊里面发送。


是的发其他消息是可以的，这个估计应该就是敏感内容的原因了，对啦请问这个插件能不能加入一个就是引用消息也能使机器人进行回复呀

**Comment by wangxyd** [comment]
CoW在调用插件之前就忽略了引用消息，必须改CoW源码才能使机器人回复引用，步骤参考这个：https://github.com/wangxyd/ipartment?tab=readme-ov-file#%E5%A4%87%E6%B3%A8

CoW开启回复引用消息之后，可以使用插件的优化引用消息的功能。

**Comment by AnCool-OvO** [comment]
> CoW在调用插件之前就忽略了引用消息，必须改CoW源码才能使机器人回复引用，步骤参考这个：https://github.com/wangxyd/ipartment?tab=readme-ov-file#%E5%A4%87%E6%B3%A8
> 
> CoW开启回复引用消息之后，可以使用插件的优化引用消息的功能。


是的这个我知道滴，可能是我没有表达清楚，我的意思是就是这个能不能实现我引用机器人消息时他也能直接进行回复不需要我在引用的时候还有@他才能进行回复，同时他回复我的时候可以引用我的消息进行回复从而不进行@了

**Comment by wangxyd** [comment]
1、这个能不能实现我引用机器人消息时他也能直接进行回复不需要我在引用的时候还有@他才能进行回复
这个是CoW决定的，你把机器人的昵称加到唤醒关键词里面就可以实现。
2、同时他回复我的时候可以引用我的消息进行回复从而不进行@了
这个理论上可以通过修改CoW源码实现。

**Comment by AnCool-OvO** [comment]
> 1、这个能不能实现我引用机器人消息时他也能直接进行回复不需要我在引用的时候还有@他才能进行回复 这个是CoW决定的，你把机器人的昵称加到唤醒关键词里面就可以实现。 2、同时他回复我的时候可以引用我的消息进行回复从而不进行@了 这个理论上可以通过修改CoW源码实现。


好的感谢回复
