### ISSUE TITLE
能否改一下引用，引用图片的话上传图片给model

### ISSUE THREAD

**Issue by lfglfg11** [wangxyd/ipartment#2]
![1714563525276](https://github.com/wangxyd/ipartment/assets/32725664/c97b2525-bee7-4c07-a9d3-f1f378f3b5ec)
目前图片引用不会上传，能否修改把引用的图片也上传上去？
因为我是gpt-4-all模型，所以识别图片没问题。
不过考虑到大部分正常的问答模型无法识别图片，要gpt-4-vison-preview或者其他识图模型才可以，所以建议改一下插件，即引用图片时让该信息走配置的4V模型，或许可以参考sum4all插件

**Comment by wangxyd** [comment]
抱歉，我暂时没有支持识图的模型可用，无法实现这个需求！
你可以参照这个项目自行实现~
